// <auto-generated />
namespace FamiLife.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tentativeManyToMany4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tentativeManyToMany4));
        
        string IMigrationMetadata.Id
        {
            get { return "201701221543167_tentativeManyToMany4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
